config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]

  root :to => 'pages#home'

  match '/contact', :to => 'pages#contact'

  match '/about',   :to => 'pages#about'

  match '/help',    :to => 'pages#help'

  match '/signup',  :to => 'users#new'

  match '/signin',  :to => 'sessions#new'

  match '/signout', :to => 'sessions#destroy'

end

app/models/micropost.rb
# == Schema Information
#
# Table name: microposts
#
#  id         :integer         not null, primary key
#  content    :string(255)
#  user_id    :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Micropost < ActiveRecord::Base
  attr_accessible :content

  belongs_to :user

  validates :content, :presence => true, :length => { :maximum => 140 }
  validates :user_id, :presence => true

  default_scope :order => 'microposts.created_at DESC'


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime        not null
#  updated_at         :datetime        not null
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean         default(FALSE)
#

require 'digest'

class User < ActiveRecord::Base
  attr_accessor   :password
  attr_accessible :email, :name, :password, :password_confirmation

  has_many :microposts, :dependent => :destroy

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence   => true,
  					:length     => { :maximum => 50 }
  validates :email, :presence   => true,
  					:format     => { :with => email_regex },
  					:uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
  					   :confirmation => true,
  					   :length => { :within => 6..40 }
  
  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def feed
    Micropost.where("user_id = ?", id)
  end

  class << self
    def authenticate(email, submitted_password)
      user = find_by_email(email)
      (user && user.has_password?(submitted_password)) ? user : nil
    end

    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end

  private 

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)    
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  
  before_filter :authenticate
  before_filter :authorized_user, :only => :destroy

	def create
	  @micropost = current_user.microposts.build(params[:micropost])
	  if @micropost.save
	  	redirect_to root_path, :flash => { :success => "Reason saved." }
	  else
	    @feed_items = []
	  	render 'pages/home'
	  end	
	end
	
	def destroy
		@micropost.destroy
		redirect_to root_path, :flash => { :success => "Reason destroyed." }
	end

	private
		def authorized_user
			@micropost = Micropost.find(params[:id])
			redirect_to root_path unless current_user?(@micropost.user)
		end
	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  	@title = "Home"
    if signed_in?
    @micropost = Micropost.new
    @feed_items = current_user.feed.page(params[:page]).per(10)
    end
  end

  def contact
  	@title = "Contact"
  end

  def about
  	@title = "About"
  end

  def help
  	@title = "Help"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  	@title = "Sign in"
  end

  def create
  	user = User.authenticate(params[:session][:email],
  							 params[:session][:password])
  	if user.nil?
  	  flash.now[:error] = "Invalid email and password combination."
  	  @title = "Sign in"
  	  render 'new'
  	else
  	  sign_in user
      redirect_back_or user
  	end
  end

  def destroy
  	sign_out
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy

  def index
    @users = User.order(:name).page(params[:page]).per(10)
    @title = "All users"
  end

  def show
  	@user = User.find(params[:id])
    @microposts = @user.microposts.page(params[:page]).per(10)
  	@title = @user.name
  end
  
  def new
  	@user = User.new
  	@title = "Sign up"
  end

  def create

  	@user = User.new(params[:user])
  	if @user.save
      sign_in @user
  	  redirect_to @user, :flash => { :success => "Welcome to Trackr!" }
  	else
  	  @title = "Sign up"
  	  render 'new'
  	end
  end

  def edit
    # @user = User.find(params[:id])
    @title = "Edit user"

  end

  def update
    # @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, :flash => { :success => "Profile updated." }
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, :flash => { :success => "User destroyed." }
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless (current_user.admin? && !current_user?(@user))
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
  	base_title = "Trackr - Track all unavail activities"
    if @title.nil?
    	base_title
    else
    	"#{base_title} | #{@title}"
    end
  end

  def logo
  	image_tag("logo.png", :alt => "Sample App", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
	  cookies.permanent.signed[:remember_token] = [user.id, user.salt]
	  current_user = user
	end

	def current_user=(user)
	  @current_user = user
	end

	def current_user
	  @current_user ||= user_from_remember_token
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		cookies.delete(:remember_token)
		current_user = nil
	end

	def current_user?(user)
		user == current_user
	end


    def authenticate
      deny_access unless signed_in?
    end
    
	def deny_access
	  store_location
      redirect_to signin_path, :notice => "Please sign in to access this page."
    end

    def store_location
    	session[:return_to] = request.fullpath
    end

    def redirect_back_or(default)
    	redirect_to(session[:return_to] || default)
    	clear_return_to
    end

    def clear_return_to
    	session[:return_to] = nil
    end


	private 

	  def user_from_remember_token
	  	User.authenticate_with_salt(*remember_token)
	  end

	  def remember_token
	  	cookies.signed[:remember_token] || [nil, nil]
	  end
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { :size => 50 })
		gravatar_image_tag(user.email.downcase, :alt => user.name, 
												:class => 'gravatar',
												:gravatar => options)
	end
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "Developer", 'http://www.facebook.com/markmarkmarkysomanymarkmynameismarked/' %></li>
		</ul>
	</nav>
	<br>
	<p class="quiet small">All rights reserved. Copyright 2012.</p>
</footer>

app/views/layouts/_header.html.erb
<header>
<%= link_to logo, root_path %>
<nav class="round"> 
	<ul>
		<li><%= link_to "Home", root_path %></li>
		<% if signed_in? %>
		<li><%= link_to "Profile", current_user %></li>
		<li><%= link_to "Users", users_path %></li>
		<li><%= link_to "Settings", edit_user_path(current_user) %></li>
		<% end %>
		<li><%= link_to "Help", help_path %></li>
		<% if signed_in? %>
		<li><%= link_to "Sign out", signout_path %></li>
		<% else %>
		<li><%= link_to "Sign in", signin_path %></li>
		<% end %>
	</ul>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	  <![endif]-->
	  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
	  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
	  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
	  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
	  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= title %> </title>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/stylesheets' %>
	  <%= javascript_include_tag "application" %>
	  <script type="text/javascript" src="/assets/jquery.js"></script>
    <script type="text/javascript" src="/assets/jquery.quovolver.js"></script>
  
    <!-- JavaScript Test Zone -->
    <script type="text/javascript">
    $(document).ready(function() {
      
      $('blockquote').quovolver();
      
    });
    </script>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/header' %>

			
			<section class="round">
				<% flash.each do |key, value| %>
				  <div class="flash <%= key %>"><%= value %></div>
				<% end %>
				<%= yield %>
			</section>
			
			<% if signed_in? %>
			<div id="bquote">
            
	            <blockquote>
	              	<p>"Life begins at the end of your comfort zone."</p>
	              	<cite>&ndash; Neal Donald Walsch</cite>
	            </blockquote>
	            
	            <blockquote>
	            	<p>"Absorb what is useful, reject what is useless, add what is specifically your own."</p> 
	            	<cite>&ndash; Bruce Lee</cite>
	            </blockquote>

	            <blockquote>
	            	<p>"Efficiency is doing things right; effectiveness is doing the right things." </p> 
	            	<cite>&ndash; Peter Drucker</cite>
	            </blockquote>

	            <blockquote>
	            	<p>“Fall seven times, Stand up eight.”</p> 
	            	<cite>&ndash; Japanese Proverb</cite>
	            </blockquote>

	            <blockquote>
					<p>“If you love life, don’t waste time, for time is what life is made up of.”</p>
	            	<cite>&ndash; Bruce Lee</cite>
	            </blockquote>

	            <blockquote>
	            	<p>“It’s not knowing what to do, it’s doing what you know.”</p> 
	            	<cite>&ndash; Tony Robbins</cite>
	            </blockquote>

	            <blockquote>
	            	<p>"Success breeds success."</p> 
	            	<cite>&ndash; Unknown</cite>
	            </blockquote>

	            <blockquote>
	            	<p>"The path to success is to take massive, determined action."</p> 
	            	<cite>&ndash; Tony Robbins</cite>
	            </blockquote>

	            <blockquote>
	            	<p>"The perfect is the enemy of the good."</p> 
	            	<cite>&ndash; Voltaire</cite>
	            </blockquote>

	            <blockquote>
	            	<p>“Words may show a man’s wit but actions his meaning.”</p> 
	            	<cite>&ndash; Benjamin Franklin</cite>
	            </blockquote>
            
              </div>
              <% end %>

			<%= render 'layouts/footer' %>

			<%= debug(params) if Rails.env.development? %>

		</div>
	</body>
</html>

app/views/microposts/_micropost.html.erb
<tr>
	<td class="micropost">
		<span class="content"><%= micropost.content %></span>
		<span class="timestamp">
			Posted <%= time_ago_in_words(micropost.created_at) %> ago.
		</span>
	</td>

	<% if current_user?(micropost.user) %>
	<td>
		<%= link_to "delete", micropost, :method => :delete,
										 :confirm => "Are you sure you want to delete?",
										 :title => micropost.content %>

	</td>
	<% end %>
</tr>

app/views/pages/about.html.erb
<h1>About</h1>
<p class="justified">In a call center, an agent has different work modes, busy on call, available, unavailable, after-call work, off- phone work, etc. <i>Unavailable</i> (a.k.a. unavail) status is when an agent is not ready to take in calls. Possible reasons are medical condition, working on a special task, defective workstation (phone, pc, mouse, amp, etc.), coaching session, etc.</p>

<p>The main objective of this website is to help agents keep track of all their unavail activities so when the push comes to shove, they can cover their a**!</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>For feedback and suggestions, kindly shoot me an email.</p>
<p>Don't forget to say something nice, ayt?</p>
<p>Email: <a href="mailto:radical.mark@gmail.com">mark_i_admire_you@somuch.com</a>, and by the way, you're welcome! ;)</p>

app/views/pages/help.html.erb
<h1>Help</h1> 
<p>Sorry, no help at all!</p>
<p>But I'm still a friend too. </p>
<p>This <a href="http://google.com">one</a> is for you.</p>

app/views/pages/home.html.erb
<% if signed_in? %>

	<table class="front" summary="For signed-in users">
		<tr>
			<td class="main">
				<h1 class="micropost">Reason for unavail?</h1>
				<%= render 'shared/micropost_form' %>
				<%= render 'shared/feed' %>
			</td>

			<td class="sidebar round">
				<%= render 'shared/user_info' %>
			</td>
		</tr>
	</table>

<% else %>

<h1 class="round center">Track all your off-phone activities here.</h1>
<p class="center">
Save yourself some time sending an email to your supervisor only to justify your unavail activity.
Sign up for an account and send the URL of your profile to your supervisor. Have your supervisor track down all your unavail activities. Less pain, more comfort! Now you will have more time dealing with the necessities!
</p>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

<p class="center small">
Register an account for free.
</p>

<br>

<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<h2>
			<%= pluralize(object.errors.count, "error") %>
			prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
			user from being saved:
		</h2>
		<p>There were problems with the following fields:</p>
		<ul>
		<% object.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>	
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<table class="microposts" summary="Status feed">
	<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
</table>
<%= paginate @feed_items %>

<% end %>

app/views/shared/_feed_item.html.erb
<tr>
	<td class="gravatar"> 
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	</td>
	<td class="micropost">
		<span class="user">
			<%= link_to feed_item.user.name, feed_item.user %>
		</span>
		
		<span class="content">
			<%= feed_item.content %>
		</span>
		
		<span class="timestamp">
			Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
		</span>
	</td>

	<% if current_user?(feed_item.user) %>
	<td>
		<%= link_to "delete", feed_item, :method => :delete,
										 :confirm => "You sure?",
										 :title => feed_item.content %>

	</td>
	<% end %>
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
		<div class="field">
		<%= f.text_area :content %>
	</div>

	<div class="actions">
		<%= f.submit "Submit" %>
	</div>
<% end %>

app/views/shared/_user_info.html.erb
<div class="user_info">
	<a href="<%= user_path(current_user) %>">
		<%= gravatar_for current_user, :size => 30 %>
		<span class="user_name">
			<%= current_user.name %>
		</span>
		<span class="microposts">
			<%= pluralize(current_user.microposts.count, "unavail counts") %>
		</span>
	</a>
</div>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>

	<div class ="field">
		<%= f.label :name %> <br />
		<%= f.text_field :name %>
	</div>

	<div class ="field">
		<%= f.label :email %> <br />
		<%= f.text_field :email %>
	</div>

	<div class ="field">
		<%= f.label :password %> <br />
		<%= f.password_field :password %>
	</div>

	<div class ="field">
		<%= f.label :password_confirmation, "Confirmation" %> <br />
		<%= f.password_field :password_confirmation %>
	</div>

app/views/users/_micropost.html.erb
<tr>
	<td class="micropost">
		<span class="content"><%= micropost.content %></span>
		<span class="timestamp">
			Posted <%= time_ago_in_words(micropost.created_at) %> ago.
		</span>
	</td>
</tr>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, :size => 30 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? %>
	|
	<%= link_to "delete", user, :method => :delete, :confirm => "Are you sure?",
								:title => "Delete #{user.name}" %>
	<% end %>
</li>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>

	<%= render 'fields', :f => f %>

	<div class ="actions">
		<%= f.submit "Update"%> <br />
	</div>
<% end %>

<div>
	<%= gravatar_for @user %>
	<a href="http://gravatar.com/emails" target=_blank>Change</a>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>

<%= paginate @users %>

<ul class="users">
	
	<%= render @users %>
	
</ul>

<%= paginate @users %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
	
	<%= render 'fields', :f => f %>

	<div class ="actions">
		<%= f.submit "Sign up" %> <br />
	</div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information"> 
	<tr>
	<td class="main"> 
		<h1>
			<%= gravatar_for @user %>
			<%= @user.name %> 
		</h1>
		<% if @user.microposts.any? %>
		  <table class="microposts" summary="User microposts">
		  	<%= render @microposts %>
		  </table>
		  <%= paginate @microposts %>
		<% end %>
	</td> 

	<td class="sidebar round">
		<strong>Name</strong> <%= @user.name %><br />
		<strong>URL</strong>  <%= link_to user_path(@user), @user %><br />
		<strong>Unavail Counts</strong> <%= @user.microposts.count %>

	</td>
	</tr> 
</table>